"""Derive the mobile crop for each course banner from the artwork itself.

The five course banners are 2064x512 (4.03:1). Rendered at the width of a phone
that is an ~87px strip: the whole frame is visible and the drawing inside it is
too small to read. Cropping the sides on narrow viewports is the standard fix,
and where to crop is not a matter of taste — it is where the artwork is.

This measures the non-ground bounding box of each banner (the same method
`frame-audit.py` uses) and writes `src/features/course-pack/banner-crops.json`:

  source       intrinsic size, so the crop window can be recomputed
  art          the artwork's bounding box as fractions of the frame
  cropAspect   the aspect ratio a narrow container should use: the window is
               `cropAspect * source height` source pixels wide, so the art fits
               with BREATHING room and nothing else is cut beyond the empty ground
  focusX       where the crop window is anchored, as a percentage of the frame —
               the artwork's own horizontal centre, clamped so the window cannot
               run off either edge

Run by hand after replacing a banner:

    python3 scripts/brand/banner-crops.py            # write
    python3 scripts/brand/banner-crops.py --check     # verify, exit 1 on drift

`tests/banner-crops.test.ts` re-derives the crop window from this file without
PIL and fails if the artwork would fall outside it; this script is where the
pixel truth comes from.
"""
from __future__ import annotations

import json
import sys
from typing import Any, cast

try:
    from PIL import Image
except ImportError:  # pragma: no cover - checked by the caller
    print("Pillow is required: python3 -m pip install Pillow")
    raise SystemExit(2)

CANVAS = (0xFB, 0xF4, 0xE6)  # --canvas, the cream the brand art is drawn on
TOL = 26  # how far from the canvas a pixel has to be to count as artwork
BREATHING = 1.06  # keep 6% of ground around the art so it does not read as a crop
FULL_ASPECT = 2064 / 512  # the banners' own ratio: the ceiling for cropAspect
OUT = "src/features/course-pack/banner-crops.json"

LANGUAGES = ["french", "italian", "german", "spanish", "portuguese"]


def art_bbox(path: str) -> tuple[tuple[int, int, int, int], tuple[int, int]]:
    im = Image.open(path).convert("RGB")
    w, h = im.size
    px = cast(Any, im.load())

    def has(x: int, y: int) -> bool:
        p = px[x, y]
        return max(abs(p[i] - CANVAS[i]) for i in range(3)) > TOL

    xs = [x for x in range(0, w, 2) if any(has(x, y) for y in range(0, h, 4))]
    ys = [y for y in range(0, h, 2) if any(has(x, y) for x in range(0, w, 4))]
    if not xs or not ys:
        raise ValueError(f"{path}: no artwork found against the canvas colour")
    # Widen by the sampling stride so the box is an outer bound, not an inner one.
    return (max(0, min(xs) - 2), max(0, min(ys) - 2), min(w, max(xs) + 3), min(h, max(ys) + 3)), (w, h)


def derive(path: str) -> dict[str, Any]:
    (x0, y0, x1, y1), (w, h) = art_bbox(path)
    art_w = x1 - x0
    # A window this wide shows the whole drawing plus breathing room, and no more.
    wanted = art_w * BREATHING / h
    crop_aspect = round(min(FULL_ASPECT, wanted), 3)
    window = crop_aspect * h
    # Where the window sits: centred on the art, then pulled inside the frame.
    # Everything here is a fraction of the frame, which is also how the browser
    # resolves `object-position` — so the numbers below are the ones the CSS uses.
    window_fraction = window / w
    art_centre = (x0 + x1) / 2 / w
    left = min(max(art_centre - window_fraction / 2, 0.0), 1.0 - window_fraction)
    # `object-position: X%` aligns X% of the image with X% of the box, so the
    # visible window's left edge lands at `X/100 * (1 - window fraction)`.
    focus = round(left / (1.0 - window_fraction) * 100, 2) if window_fraction < 1 else 50.0
    return {
        "source": {"width": w, "height": h},
        "art": {
            "x": round(x0 / w, 4),
            "y": round(y0 / h, 4),
            "width": round(art_w / w, 4),
            "height": round((y1 - y0) / h, 4),
        },
        "cropAspect": crop_aspect,
        "focusX": focus,
    }


def build() -> dict[str, Any]:
    return {
        "*": (
            "Generated by scripts/brand/banner-crops.py from the pixels of each "
            "banner. cropAspect and focusX are the narrow-viewport crop: the "
            "artwork's own bounding box plus 6% breathing room, anchored on its "
            "horizontal centre. Do not hand-edit; re-run the script after "
            "replacing a banner."
        ),
        "fullAspect": round(FULL_ASPECT, 3),
        "courses": {slug: derive(f"public/brand/courses/{slug}.jpg") for slug in LANGUAGES},
    }


def main() -> int:
    data = build()
    rendered = json.dumps(data, indent=2) + "\n"
    if "--check" in sys.argv:
        try:
            current = open(OUT).read()
        except FileNotFoundError:
            print(f"{OUT} is missing; run python3 scripts/brand/banner-crops.py")
            return 1
        if current != rendered:
            print(f"{OUT} is stale; run python3 scripts/brand/banner-crops.py")
            return 1
        print(f"{OUT} matches a fresh measurement of every banner")
        return 0

    with open(OUT, "w") as handle:
        handle.write(rendered)
    for slug, crop in data["courses"].items():
        art = crop["art"]
        print(
            f"{slug:11s} art {art['width'] * 100:4.0f}% x {art['height'] * 100:4.0f}%  "
            f"cropAspect {crop['cropAspect']:.2f}  focusX {crop['focusX']:5.1f}%  "
            f"window {crop['cropAspect'] * crop['source']['height']:.0f}px of {crop['source']['width']}"
        )
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
